/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'eduardo.carvalho' at '25/07/18 11:48' with Gradle 2.7
 *
 * @author eduardo.carvalho, @date 25/07/18 11:48
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
